services:
- docker
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" > ~/.netrc
- cd ..
- git clone --single-branch --branch master https://github.com/tulibraries/ansible-playbook-solrcloud.git
- mkdir -p ansible-playbook-solrcloud/data/tmp/collections
- cp -r tul_cob-az-solr ansible-playbook-solrcloud/data/tmp/collections/
install:
- cd ansible-playbook-solrcloud
- make build
- bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:8090/solr)"
  != "302" ]]; do sleep 5; done'
- make create-local-collections
- make create-aliases
- cd ..
script:
- curl http://localhost:8081/solr/tul_cob-az/admin/ping | jq .status
after_success:
- true
before_deploy:
- cd tul_cob-az-solr
deploy:
- provider: script
  script: bash .travis/deploy-stage.sh
  on:
    branch: master
- provider: script
  script: bash .travis/deploy-prod.sh
  on:
    tags: true
    branch:
    - "/^[0-9]$/"
notifications:
  slack:
    rooms:
    - secure: t2abp4n0V4MbZoWj3wnYq5HgB8eednKfGJryJsvYUkhlmXSu6kr+P1RtrAPxUpK1IeH4rjpVLIFfRgEaV9WlMP/8A4Vedc4SgFJTpZ1WjGW0BFk0jndbrHsJ5UogqHnjA1kq7PTg5JRg8K1MZiasNko/MEhGlIUGVp7BN9bNJVj/fP4KiMCF1NM23TB/a5G3eKu9PB2Xaz6nEoucbcwTJU2ns8qi1Ow1IFHqe4832nDnrztogbnH18423v727ce2J2+cuv9Xc+i07CNg8A5W8sWSrAEHytNprciOOvignbHlNMUb9iBZx0TV6Xu6Cy2dbUOpo95ItgTykiXgFDnJWOphQVMPPsrsUxM5eMjbh/da6A34WpStQdiTS0idQjfpOO3vz8vHAyOsIubl/cwvg9qkXgwRqOtU7HXFShqY7FFvPe8NP7ZeHhV2VL8vGpEZ1PzfidiFgux2sVcZPEXEX3L3lDAsCspzNJq8KH/aTshD6le0XloYGyPu2JxUBsr+HauLnI/a1Z2HTHRgK0SF/6NQP+IcIMurMx3RTjbAcpWOLHt4fAAL8XS/8RiwleG55gHNchKhpwb7tzmbHTuwXiDkI18nl1An70vHfUh2duZL+LbVcdHXaAiT+vbYZtLoNOuYaUd0dnl7EjeB4O7LtVDBO1BNrpuu+HsOI4A7NTg=
    - secure: LvfhiKQd8OGrJ6TTIC/Gwkuj90WoZitApB4UPxJZZD7Vz63YhAl7T8gXKcMEymwEAkEO0SWOkghasEh06SJqcdjvnpYVDAEMZPepHqpFmOMGLQvjqKVhtZSP62mquusu1wP8dtNseng5Tj2uAIqf4QfZyWI/p5MZkZ8obbLlCupudx6MYCDko5RwQqJntA3uFkJcI/iuHtJ7yxi7zdJJwiWmNuKEwX5PLFJguqMyA/RU6HvsPlNdWwqMsaMLNCINxP8AP91XqyjRIncZ/2+n4wILE0NQKp4sS9bWHB/VP5mLfg5NIBF29XM+atW+njjPxgU1gGyp/ceLTIOvWmkH0jEUk6mNSidK+w13ikY3weZF+O58e7LzrO22DXyWpQ5KrU2vCT/w0Av/vOYteSZj+B4yDo4lz3j+JilDvvgIdzVWMdugu9MUGzlx8cpyC0Hit7oqDyFdJ/sl0dy9eI8IS9fDMOl9w3Xt6iyuI1QXIpUuUKaxkbK7ot6BPU1zxVOs6aSRBVXNoOo/hyYiUnmuO/MP216GWup8IJLVcShWive/vg+8uDkocho/mEgf6NAmp5raC+UA4M5liKJjvAx5f2ejfxD5NNL1itFutUtDSTTXzgxNOuFNotKN1/YavT7uox+4Dd7WdNkVN3gvcgu8h3HGg4T3h6r3LgYLDgNUeZ0=
env:
  global:
    secure: nwKgBCd5uZZ2Aj2vQF2jSP/o+KfUs4BdQcwCMMNDeV24l1S6dYuASmDbgA087+rxEhS89LBQ+txV6VAfuTuYL2DHDv1xqzTpEPLgdIMFYpD07OwriU3+JYS4SwoZS9bG3h6Jax5ppyz4GBb4Bm0d+ky7M18+XfhoAz27axDTzEfrbw+VTShud+N+ozQFu/N6dl4HX6L+LqctNBkad2CNOwmPQVYms2wWNRQ7LNhJZjKdg5AFuMK25MmLDMtefFKsnceByGT6tmyeDzzH2qhsMxGS6HbV2guNmS4tBxzsMyoaVMbRCnS3cD2+S2PhUmsi2ACNQ9VaSSxZklEo/Y7fKaz5pBAvl6QJ19oaeO5dP5y+1EtHt+IEh006KGCK1UetiehvbTjN20zMgQ/QGBTfH1HlYLwNks553uUa6VEoPZjAVeNIAx4iZEIg1oC+usVIthPuWwM/c1DBDsEoFkgGAleiSuDSQhCjNshQdmnYKIOu+NuBlPSIUHVPyp+z5IX4P/a8VbNFAiJSSahO0lcIa7CXfokhQ5L+KdLlEZUl7MBZJEkfcWqiZDRdJEp9PpqpoIc6JpJo7BzV6dzQI518mLWBrUOUagzymXga638+aP7s/FNnD59DpNFFd+ar4X/9l0O09AQ6gcJYRs7hUoXFhp0P9aeuj9UyTmQfk8RJRVA=
