version: 2

workflows:
  version: 2
  test:
    jobs:
      - run_tests
  deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*-[A-z0-9]+$/
      - run_deploy:
          requires:
            - run_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*-[A-z0-9]+$/
  prod_deploy:
    jobs:
      - run_tests:
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-[A-z0-9]+$/

      - request-prod-deploy:
          type: approval
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-[A-z0-9]+$/
      - run_deploy:
          requires:
            - run_tests
            - request-prod-deploy
          filters:
            branches:
              ignore: /.*/
            tags:
              ignore: /.*-[A-z0-9]+$/

jobs:
  run_tests:
    machine: true

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:d3:45:4c:e5:31:4e:cd:64:c0:e3:2a:73:a3:55:94"
      - run:
          name: Set up a local Solr with build's solr config.
          command: bash .circleci/setup_solr.sh
      - run:
          name: Test that we can get to the solr collection successfully.
          command: bash .circleci/test.sh

  run_deploy:
    docker:
      - image: circleci/python:3.6.6
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "59:d3:45:4c:e5:31:4e:cd:64:c0:e3:2a:73:a3:55:94"
      - run:
          name: Build configuration asset
          command: bash .circleci/build.sh
      - run:
          name: Deploy configuration asset to SolrCloud
          command: bash .circleci/deploy.sh
