name: Deploy

on:
  push:
    tags:
      - "[0-9]+"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SOLR_USER: ${{ secrets.SOLR_USER }}
      SOLR_PASSWORD: ${{ secrets.SOLR_PASSWORD }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_TAG: ${{ github.ref_name }}
    strategy:
      matrix:
        python-version: [ "3.12" ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.10.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Build configuration asset
      run: make zip-gh
    
    - name: Deploy configuration asset to SolrCloud
      run: bash .github/scripts/deploy.sh
